name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v1.25.0  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v1.25.0'  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v1.25.0"  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v1.25.0
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v1.25.0'
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v1.25.0"
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v1.25.0 # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v1.25.0' # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v1.25.0" # hello
