name: test

on:
  pull_request:
    branches: [dummy]
  push:
    branches: [dummy]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v1.37.2  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v1.37.2'  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v1.37.2"  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v1.37.2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v1.37.2'
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v1.37.2"
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v1.37.2 # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v1.37.2' # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v1.37.2" # hello
