name: test

on:
  pull_request:
    branches: [dummy]
  push:
    branches: [dummy]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.8.9  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v0.8.9'  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v0.8.9"  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.8.9
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v0.8.9'
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v0.8.9"
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.8.9 # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v0.8.9' # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v0.8.9" # hello
