name: test

on:
  pull_request:
    branches: [dummy]
  push:
    branches: [dummy]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.10.2  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v0.10.2'  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v0.10.2"  # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.10.2
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v0.10.2'
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v0.10.2"
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: v0.10.2 # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: 'v0.10.2' # hello
      - uses: aquaproj/aqua-installer@v0.4.0
        with:
          aqua_version: "v0.10.2" # hello
